const CANDIDATES = [
  {
    id: "hd42-okerlund-williams",
    race: "House District 42 — Sandy",
    level: "State",
    county: "Salt Lake",
    caseNumber: "CASE 07",
    names: "Okerlund vs. Williams",
    verdict: "The Water Bill That Didn't Survive",
    tags: ["PAC Pipeline", "Water Bill Died", "Platform vs. Record"],
    stamp: "Active",
    href: "hd42-okerlund-williams.html"
  },
  {
    id: "hd12-graff-schultz",
    race: "House District 12 — Roy / Hooper",
    level: "State",
    county: "Weber",
    caseNumber: "CASE 06",
    names: "Graff vs. Schultz",
    verdict: "The Three-PAC Ecosystem",
    tags: ["Speaker of the House", "PAC Network", "Platform vs. Record"],
    stamp: "Active",
    href: "hd12-graff-schultz.html"
  },
  {
    id: "hd11-calder-hall",
    race: "House District 11 — Washington Terrace / Riverdale",
    level: "State",
    county: "Weber",
    caseNumber: "CASE 05",
    names: "Calder vs. Hall",
    verdict: "The Stock Portfolio That Funds Her Campaign",
    tags: ["Stock Overlap", "Disclosure Gap", "PAC Funding"],
    stamp: "Active",
    href: "hd11-calder-hall.html"
  },
  {
    id: "hd10-lesser-alvey",
    race: "House District 10 — East / South Ogden",
    level: "State",
    county: "Weber",
    caseNumber: "CASE 04",
    names: "Lesser vs. Alvey",
    verdict: "The Nonprofit That Wasn't",
    tags: ["Open Seat", "Corporate Filing", "PAC Network"],
    stamp: "Active",
    href: "hd10-lesser-alvey.html"
  },
  {
    id: "hd9-choberka-sawyer",
    race: "House District 9 — West Haven",
    level: "State",
    county: "Weber",
    caseNumber: "CASE 03",
    names: "Choberka vs. Sawyer",
    verdict: "The Vendor Loop",
    tags: ["Vendor Network", "Deletion Pattern", "Rematch"],
    stamp: "Active",
    href: "hd9-choberka-sawyer.html"
  },
  {
    id: "hd8-kyle-james-shelton",
    race: "House District 8 — Ogden Valley",
    level: "State",
    county: "Weber",
    caseNumber: "CASE 02",
    names: "Kyle vs. James vs. Shelton",
    verdict: "The Career Total vs. The Six-Contribution Cycle",
    tags: ["Three-Way Race", "Judicial Bills", "Promise vs. Record"],
    stamp: "Active",
    href: "jason-kyle-hd8.html"
  },
  {
    id: "hd7-mittendorf-wilcox",
    race: "House District 7 — North Ogden",
    level: "State",
    county: "Weber",
    caseNumber: "CASE 01",
    names: "Mittendorf vs. Wilcox",
    verdict: "The Uncle, The PAC, and the Amendment Pattern",
    tags: ["Family Network", "PAC Money Flow", "Amendment Rate"],
    stamp: "Active",
    href: "hd7-mittendorf-wilcox.html"
  },
  {
    id: "joseph-kerry",
    race: "Utah State Board of Education — District 2",
    level: "State",
    county: "Weber",
    caseNumber: "CASE 00",
    names: "Kerry vs. Weaver",
    verdict: "The Path Forward Utah Network",
    tags: ["COI Omissions", "PAC Network", "USBE"],
    stamp: "Active",
    href: "joseph-kerry.html"
  },
  {
    id: "davis-county-lee-millburn",
    race: "Davis County Commission — Seat A & Seat B",
    level: "County",
    county: "Davis",
    caseNumber: "CASE 08",
    names: "Lee vs. Millburn",
    verdict: "Self-Funded vs. Unfiled",
    tags: ["Campaign Finance Gap", "Platform vs. Record", "Unopposed Seat"],
    stamp: "Active",
    href: "davis-county-commission-2026.html"
  }
];
