const CANDIDATES = [
  {
    id: "questions-every-candidate",
    race: "Statewide — All 2026 Candidates",
    level: "Resource",
    caseNumber: "RESOURCE 03",
    names: "The Weber County Hive Questionnaire",
    verdict: "Questions Every Utah Candidate Should Answer",
    tags: ["Candidate Questionnaire", "13 Questions", "Statewide"],
    stamp: "Pinned",
    href: "six-questions-every-candidate.html",
    pinned: true,
    datePosted: "2026-09-15",
    dateUpdated: "2026-09-15"
  },
  {
    id: "questions-for-incumbents",
    race: "Statewide — Legislative Voting Record Questions",
    level: "Resource",
    caseNumber: "RESOURCE 02",
    names: "Dr. Ronald Mortensen, Citizens for Tax Fairness",
    verdict: "Questions for Incumbents",
    tags: ["Reader-Submitted", "Voting Record", "MIDA / PID"],
    stamp: "Pinned",
    href: "questions-for-incumbents.html",
    pinned: true,
    datePosted: "2026-09-15",
    dateUpdated: "2026-09-15"
  },
  {
    id: "fifth-fifth-sales-tax",
    race: "Davis County — Proposed Countywide Sales Tax",
    level: "Resource",
    caseNumber: "RESOURCE 01",
    names: "Dr. Ronald Mortensen, Citizens for Tax Fairness",
    verdict: "The Fifth-Fifth Sales Tax",
    tags: ["Reader-Submitted", "Talking Points", "Davis County"],
    stamp: "Pinned",
    href: "fifth-fifth-sales-tax.html",
    pinned: true,
    datePosted: "2026-09-15",
    dateUpdated: "2026-09-15"
  },
  {
    id: "sd6-tran-neal",
    race: "Senate District 6 — Davis County (Kaysville area)",
    level: "State",
    county: "Davis",
    caseNumber: "CASE 21",
    names: "Tran vs. Neal",
    verdict: "The Deciding Vote",
    tags: ["Tie-Breaking Tax Vote", "Disclosure Gap", "Meta PAC", "Doers Network", "Platform vs. Record"],
    stamp: "Active",
    href: "sd6-tran-neal.html",
    datePosted: "2026-09-23",
    dateUpdated: "2026-09-23"
  },
  {
    id: "hd16-stevenson-treasure",
    race: "House District 16 — Layton / South Weber",
    level: "State",
    county: "Davis",
    caseNumber: "CASE 19",
    names: "Stevenson vs. Treasure",
    verdict: "Sixteen to One",
    tags: ["Fundraising Gap", "PAC Network", "Family Funding", "Northern Utah Economic Alliance", "Board Overlap"],
    stamp: "Active",
    href: "hd16-stevenson-treasure.html",
    datePosted: "2026-09-21",
    dateUpdated: "2026-09-22"
  },
  {
    id: "hd13-craythorne-anderson",
    race: "House District 13 — Clearfield / Clinton / West Point",
    level: "State",
    county: "Davis",
    caseNumber: "CASE 13",
    names: "Craythorne vs. Anderson vs. De Mille",
    verdict: "Two LLCs and a Sitting Speaker",
    tags: ["Speaker Business Partner", "Disclosure Gap", "Three-Way Money Contrast"],
    stamp: "Active",
    href: "hd13-craythorne-anderson.html",
    datePosted: "2026-09-10",
    dateUpdated: "2026-09-10"
  },
  {
    id: "hd42-okerlund-williams",
    race: "House District 42 — Sandy",
    level: "State",
    county: "Salt Lake",
    caseNumber: "CASE 07",
    names: "Okerlund vs. Williams",
    verdict: "The Water Bill That Didn't Survive",
    tags: ["PAC Pipeline", "Water Bill Died", "Platform vs. Record"],
    stamp: "Active",
    href: "hd42-okerlund-williams.html"
  },
  {
    id: "hd12-graff-schultz",
    race: "House District 12 — Roy / Hooper",
    level: "State",
    county: "Weber",
    caseNumber: "CASE 06",
    names: "Graff vs. Schultz",
    verdict: "The Three-PAC Ecosystem",
    tags: ["Speaker of the House", "PAC Network", "Platform vs. Record"],
    stamp: "Active",
    href: "hd12-graff-schultz.html"
  },
  {
    id: "hd11-calder-hall",
    race: "House District 11 — Washington Terrace / Riverdale",
    level: "State",
    county: "Weber",
    caseNumber: "CASE 05",
    names: "Calder vs. Hall",
    verdict: "The Stock Portfolio That Funds Her Campaign",
    tags: ["Stock Overlap", "Disclosure Gap", "PAC Funding"],
    stamp: "Active",
    href: "hd11-calder-hall.html"
  },
  {
    id: "hd10-lesser-alvey",
    race: "House District 10 — East / South Ogden",
    level: "State",
    county: "Weber",
    caseNumber: "CASE 04",
    names: "Lesser vs. Alvey",
    verdict: "The Nonprofit That Wasn't",
    tags: ["Open Seat", "Corporate Filing", "PAC Network"],
    stamp: "Active",
    href: "hd10-lesser-alvey.html"
  },
  {
    id: "hd9-choberka-sawyer",
    race: "House District 9 — West Haven",
    level: "State",
    county: "Weber",
    caseNumber: "CASE 03",
    names: "Choberka vs. Sawyer",
    verdict: "The Vendor Loop",
    tags: ["Vendor Network", "Deletion Pattern", "Rematch"],
    stamp: "Active",
    href: "hd9-choberka-sawyer.html"
  },
  {
    id: "hd8-kyle-james-shelton",
    race: "House District 8 — Ogden Valley",
    level: "State",
    county: "Weber",
    caseNumber: "CASE 02",
    names: "Kyle vs. James vs. Shelton",
    verdict: "The Career Total vs. The Six-Contribution Cycle",
    tags: ["Three-Way Race", "Judicial Bills", "Promise vs. Record"],
    stamp: "Active",
    href: "jason-kyle-hd8.html"
  },
  {
    id: "hd7-mittendorf-wilcox",
    race: "House District 7 — North Ogden",
    level: "State",
    county: "Weber",
    caseNumber: "CASE 01",
    names: "Mittendorf vs. Wilcox",
    verdict: "The Uncle, The PAC, and the Amendment Pattern",
    tags: ["Family Network", "PAC Money Flow", "Amendment Rate"],
    stamp: "Active",
    href: "hd7-mittendorf-wilcox.html"
  },
  {
    id: "joseph-kerry",
    race: "Utah State Board of Education — District 2",
    level: "State",
    county: "Weber",
    caseNumber: "CASE 00",
    names: "Kerry vs. Weaver",
    verdict: "The Path Forward Utah Network",
    tags: ["COI Omissions", "PAC Network", "USBE"],
    stamp: "Active",
    href: "joseph-kerry.html"
  },
  {
    id: "davis-county-lee-millburn",
    race: "Davis County Commission — Seat A & Seat B",
    level: "County",
    county: "Davis",
    caseNumber: "CASE 08",
    names: "Lee vs. Millburn",
    verdict: "Self-Funded vs. Unfiled",
    tags: ["Campaign Finance Gap", "Platform vs. Record", "Unopposed Seat"],
    stamp: "Active",
    href: "davis-county-commission-2026.html"
  },
  {
    id: "wasatch-seat-a-kahler",
    race: "Wasatch County Council — Seat A (At-Large)",
    level: "County",
    county: "Wasatch",
    caseNumber: "CASE 09",
    names: "Kahler vs. McNeill vs. Hewlett vs. Taylor",
    verdict: "The Form She Left Blank",
    tags: ["Disclosure Gap", "Four-Candidate Field", "Park Campaign"],
    stamp: "Active",
    href: "rachel-kahler-wasatch-seat-a.html",
    datePosted: "2026-09-01",
    dateUpdated: "2026-09-11"
  },
  {
    id: "wasatch-seat-c-rowland",
    race: "Wasatch County Council — Seat C",
    level: "County",
    county: "Wasatch",
    caseNumber: "CASE 10",
    names: "Rowland vs. Folmer",
    verdict: "The Wrong Form, Four Times",
    tags: ["MIDA Board", "Write-In Challenger", "Disclosure Gap"],
    stamp: "Active",
    href: "erik-rowland-seat-c.html",
    datePosted: "2026-09-02",
    dateUpdated: "2026-09-11"
  },
  {
    id: "hd59-searle-johnson",
    race: "Utah House District 59 — Summit / Wasatch",
    level: "State",
    county: "Wasatch",
    caseNumber: "CASE 11",
    names: "Searle vs. Johnson",
    verdict: "Half the Ledger, Six PACs",
    tags: ["PAC Network", "Open Seat", "Fundraising"],
    stamp: "Active",
    href: "luke-searle-hd59.html"
  },
  {
    id: "box-elder-seat-a-smith-williams",
    race: "Box Elder County Commission — Seat A",
    level: "County",
    county: "Box Elder",
    caseNumber: "CASE 12",
    names: "Smith vs. Williams",
    verdict: "Twenty Dollars In, Thirteen Thousand Out",
    tags: ["Campaign Finance Gap", "Business Network", "Voting Record"],
    stamp: "Active",
    href: "box-elder-seat-a-smith-williams.html"
  },
  {
    id: "doers-network",
    race: "Doers Network — Statewide Endorsement & PAC Network",
    level: "State",
    county: "Statewide",
    caseNumber: "CASE 14",
    names: "Doers Network",
    verdict: "36 Endorsed. 13 Paid Who Weren't.",
    tags: ["PAC Network", "Board Overlap", "22-Member Board"],
    stamp: "Active",
    href: "doers-network.html"
  },
  {
    id: "slco-d3-bird-maynes",
    race: "Salt Lake County Council — District 3",
    level: "County",
    county: "Salt Lake",
    caseNumber: "CASE 15",
    names: "Bird vs. Maynes",
    verdict: "Family Money and a Chair's Blessing",
    tags: ["Doers Network", "Family Funding", "Succession"],
    stamp: "Active",
    href: "mike-bird-slco.html"
  },
  {
    id: "sd5-koford-hernandez",
    race: "Senate District 5 — Davis / Morgan / Weber",
    level: "State",
    county: "Weber",
    caseNumber: "CASE 16",
    names: "Koford vs. Hernandez",
    verdict: "The Seat Her Own PAC Built",
    tags: ["PAC Network", "Irish Elk LLC", "Legislative Record: D"],
    stamp: "Active",
    href: "sd5-koford-hernandez.html",
    datePosted: "2026-09-10",
    dateUpdated: "2026-09-10"
  },
  {
    id: "wasatch-seat-c-rowland-folmer",
    race: "Wasatch County Council — Seat C",
    level: "County",
    county: "Wasatch",
    caseNumber: "CASE 17",
    names: "Rowland vs. Folmer",
    verdict: "One Disclosed. One Didn't.",
    tags: ["Disclosure Gap", "Write-In Challenger", "Legislative Record: D"],
    stamp: "Active",
    href: "rowland-folmer-seat-c.html",
    datePosted: "2026-09-11",
    dateUpdated: "2026-09-11"
  },
  {
    id: "ut2-crosby-statement",
    race: "US House District 2 (Utah)",
    level: "Statement",
    caseNumber: "STATEMENT 01",
    names: "Peter Crosby",
    verdict: "In His Own Words: What Sets Him Apart from Blake Moore",
    tags: ["Candidate Statement", "UT-2"],
    stamp: "Active",
    href: "crosby-statement-ut2.html",
    datePosted: "2026-09-12",
    dateUpdated: "2026-09-12"
  },
  {
    id: "kennedy-larsen-burt-ut4",
    race: "US House District 4 (Utah)",
    level: "Federal",
    county: "Statewide",
    caseNumber: "CASE 18",
    names: "Kennedy vs. Larsen vs. Burt",
    verdict: "A First Term, A Redrawn District, A Half-Million-Dollar Gap",
    tags: ["Redistricting", "Disclosure Gap", "State-Federal Pattern"],
    stamp: "Active",
    href: "mike-kennedy-jonny-larsen-ut4.html",
    datePosted: "2026-09-13",
    dateUpdated: "2026-09-13"
  },
  {
    id: "layton-shuffle",
    race: "Layton / South Weber — Six-Seat Turnover Network",
    level: "State",
    county: "Davis",
    caseNumber: "CASE 20",
    names: "The Layton Shuffle",
    verdict: "Six Seats, One Cycle, One Family Name",
    tags: ["Seat Turnover", "Cross-Race Diagram", "Stevenson Network", "Doers Network", "Northern Utah Economic Alliance"],
    stamp: "Active",
    href: "layton-shuffle.html",
    datePosted: "2026-09-22",
    dateUpdated: "2026-09-22"
  }
];
